// <auto-generated />
using System;
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("BackendAPI.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BackendAPI.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AudienceAgeMax")
                        .HasColumnType("integer");

                    b.Property<int>("AudienceAgeMin")
                        .HasColumnType("integer");

                    b.Property<string>("AudienceGender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedByAgencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByBrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("MarketId")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumFollowers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumFollowers")
                        .HasColumnType("integer");

                    b.Property<int?>("NicheId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TargetPlatform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAgencyId");

                    b.HasIndex("CreatedByBrandId");

                    b.HasIndex("MarketId");

                    b.HasIndex("NicheId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("BackendAPI.Models.CampaignInfluencer", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfluencerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchReason")
                        .HasColumnType("text");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CampaignId", "InfluencerId");

                    b.HasIndex("InfluencerId");

                    b.ToTable("CampaignInfluencers");
                });

            modelBuilder.Entity("BackendAPI.Models.Influencer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<decimal>("BotScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid?>("DiscoveredFromInfluencerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiscoverySource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastDataRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NextRefreshDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NicheId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RefreshPriority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TikTokHandle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitterHandle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("YouTubeHandle")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("InstagramHandle");

                    b.HasIndex("MarketId");

                    b.HasIndex("NicheId");

                    b.ToTable("Influencers");
                });

            modelBuilder.Entity("BackendAPI.Models.InfluencerCollaboration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CollabDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InfluencerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("InfluencerId");

                    b.ToTable("InfluencerCollaborations");
                });

            modelBuilder.Entity("BackendAPI.Models.Markets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarketName")
                        .IsUnique();

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("BackendAPI.Models.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MessageTemplates");
                });

            modelBuilder.Entity("BackendAPI.Models.MetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageReach")
                        .HasColumnType("integer");

                    b.Property<decimal>("BotScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("EngagementRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("InfluencerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InfluencerId");

                    b.ToTable("MetricSnapshots");
                });

            modelBuilder.Entity("BackendAPI.Models.Niches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NicheName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NicheName")
                        .IsUnique();

                    b.ToTable("Niches");
                });

            modelBuilder.Entity("BackendAPI.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfluencerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCustomMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BackendAPI.Models.Campaign", b =>
                {
                    b.HasOne("BackendAPI.Models.Agency", "CreatedByAgency")
                        .WithMany("Campaigns")
                        .HasForeignKey("CreatedByAgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackendAPI.Models.Brand", "CreatedByBrand")
                        .WithMany("Campaigns")
                        .HasForeignKey("CreatedByBrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackendAPI.Models.Markets", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId");

                    b.HasOne("BackendAPI.Models.Niches", "Niche")
                        .WithMany()
                        .HasForeignKey("NicheId");

                    b.Navigation("CreatedByAgency");

                    b.Navigation("CreatedByBrand");

                    b.Navigation("Market");

                    b.Navigation("Niche");
                });

            modelBuilder.Entity("BackendAPI.Models.CampaignInfluencer", b =>
                {
                    b.HasOne("BackendAPI.Models.Campaign", "Campaign")
                        .WithMany("MatchedInfluencers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Influencer", "Influencer")
                        .WithMany("Campaigns")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("BackendAPI.Models.Influencer", b =>
                {
                    b.HasOne("BackendAPI.Models.Markets", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Niches", "Niche")
                        .WithMany()
                        .HasForeignKey("NicheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Niche");
                });

            modelBuilder.Entity("BackendAPI.Models.InfluencerCollaboration", b =>
                {
                    b.HasOne("BackendAPI.Models.Influencer", "Influencer")
                        .WithMany("PreviousCollaborations")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("BackendAPI.Models.MetricSnapshot", b =>
                {
                    b.HasOne("BackendAPI.Models.Influencer", "Influencer")
                        .WithMany("MetricSnapshots")
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("BackendAPI.Models.Agency", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("BackendAPI.Models.Brand", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("BackendAPI.Models.Campaign", b =>
                {
                    b.Navigation("MatchedInfluencers");
                });

            modelBuilder.Entity("BackendAPI.Models.Influencer", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("MetricSnapshots");

                    b.Navigation("PreviousCollaborations");
                });
#pragma warning restore 612, 618
        }
    }
}
